name: Build Github Pages
on:
  push:
    branches:
      - 'master'
      - $default-branch
      - 'dev/*'

  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install requirements
        run: DEBIAN_FRONTEND=noninteractive sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install make texlive-xetex texlive-lang-cjk
      - name: Build
        run: make pdf
      - name: Organize files
        run: mv resume-zh_CN.pdf site/
      - name: Upload
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: site/

  deploy:
    if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4